export interface IDatosMascota{
    nombreMascota :string,
    especie :string,
    raza :string,
    sexo :string,
    fechaNacimiento :string,
    celular : number,
    email  :string,
    c_cara :string,
    c_nariz :string,
    c_oreja :string,
    c_mandibula_inferior :string,
    c_mandibula_superior :string,
    c_pecho :string,
    c_espalda :string,
    c_pata_delantera_derecha :string,
    c_pata_delantera_izquierda :string,
    c_pata_trasera_derecha :string,
    c_pata_trasera_izquierda :string,
    c_cola :string,
    c_ojos  :string,
    direccion :string,
    foto_mascota :string,

    sobremi_1 :string,
    sobremi_2 :string,
    vacunas :string,
    juguetes :string,
    comida :string,
    lugar_paseo :string,
}